# Generated by Django 3.2.9 on 2021-12-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('category', models.EmailField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(default='static/img/default.jpg', upload_to='images/')),
            ],
        ),
    ]
